### ISSUE TITLE
Change Icon of AppSidebar

### ISSUE THREAD

**Issue by jotoeri** [nextcloud-libraries/nextcloud-vue#2804]
As of https://github.com/nextcloud/forms/issues/717, @nimishavijay proposed to change the hamurger-menu of the AppSidebar to a three-dot menu.

Afaik there were several complaints before, that the sidebar is not clearly recognized with the hamurger-menu. Thus, the three-dot menu could be a solution, might however interfer with apps having another three-dot menu next to the sidebar-icon?

**Comment by jotoeri** [comment]
Material design has the specific `menu-open` icon. How about using this one for the AppSidebar?
@nextcloud/designers @skjnldsv @jancborchardt @nimishavijay 

![icon](https://user-images.githubusercontent.com/47433654/183291004-e589f82f-1867-4439-bd97-5852316e2f08.png)

![Screenshot from 2022-08-07 14-42-20](https://user-images.githubusercontent.com/47433654/183291053-47a5e5d3-107b-412d-a5bb-f3a460a7e090.png)

**Comment by raimund-schluessler** [comment]
Would be nice to have a menu-close icon, when the menu is open. But since there isn't, maybe vertically mirror the icon🙈

**Comment by stefan-niedermann** [comment]
What about the [`View Sidebar`](https://fonts.google.com/icons?selected=Material+Icons&icon.query=sidebar) material icon? 🙈 
![baseline_view_sidebar_black_24dp](https://user-images.githubusercontent.com/4741199/183292850-eae0af9c-5de5-43c3-920f-1b05f63701d6.png)

**Comment by skjnldsv** [comment]
Ping @jancborchardt @nimishavijay

**Comment by nimishavijay** [comment]
The current icon used for the AppSidebar in Forms is the `menu-open` icon which is used as the icon for the navigation also, which can be a bit confusing. a different icon to toggle the sidebar is used in Talk (hamburger icon), Forms (menu-open), Collectives (legacy sidebar icon), Notes (not in the top right corner but in the 3dot menu of a note. Uses page-layout-sidebar-right). We should unify all of these since the sidebar has essentially the same content. Here is what seems suitable so far:
- [ ] [view-sidebar](https://fonts.google.com/icons?selected=Material%20Icons%3Aview_sidebar%3A) as @stefan-niedermann suggested
- [ ] [format-list-bulleted](https://fonts.google.com/icons?selected=Material%20Icons%3Aformat_list_bulleted%3A)
- [ ] [apps](https://fonts.google.com/icons?selected=Material%20Icons%3Aapps%3A)
- [ ] [space-dashboard](https://fonts.google.com/icons?selected=Material%20Icons%3Aspace_dashboard%3A)

what do you think? @nextcloud/designers

**Comment by skjnldsv** [comment]
view-sidebar or space-dashboard for me

**Comment by susnux** [comment]
Agree with *skjnldsv*, `apps` look like the grid view toggle on the files app (same position as you would expect the sidebar button).
And `format-list-bulleted` looks like the forms app logo, so for forms that would be a not that good.

**Comment by marcoambrosini** [comment]
What's wrong with menu-open? There's no need for a menu-close icon since we have a close button within the sidebar itself.

**Comment by nimishavijay** [comment]
`menu-open` is used as the icon to close the navigation, so ideally we have distinct icons on the screen. 
I would vote for `space-dashboard` because it seems more similar to the current layout of the sidebar and it's rounder, like our UI :) And agreed with the point about this being only a default and not mandatory!

**Comment by ShGKme** [comment]
Fixed in the linked PR with customization available if needed.
