### ISSUE TITLE
Use more height for action menus if available

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud-libraries/nextcloud-vue#3842]
On the left I’m in a Talk call, and it looks like all the entries in the action menu are visible. However it is scrollable with some entries below, which is not obvious at all and easily missed.

Is it possible to make it so that the height of the menu is not solely calculated based on percentage or viewport height, but also always making sure that the last entry is cut off in half so it is obvious there are more entries? See on the right as it appears in Text (of course this is by chance, just as example).

Menu still has entries, but doesn’t seem like it | With a half-cut last entry, it is clear the menu still has entries
-|-
![image](https://user-images.githubusercontent.com/925062/222138118-f3213623-7c34-40ad-93b7-ecb30d29a166.png)|![image](https://user-images.githubusercontent.com/925062/222152670-075237aa-5de3-4b84-8dfd-abbdeace06a9.png)

**Comment by jancborchardt** [comment]
Thinking about this more – actually when we still have viewport height available, we should actually just show the rest of the menu. Often it’s just 1 or 2 entries cut off, whereas still half of the vertical viewport is still available.

**Comment by szaimen** [comment]
Wouldn't adding a scrollbar also help making visible that there are more items?

I wonder why no scrollbar is visible for you..   for me it is: https://github.com/nextcloud/nextcloud-vue/issues/3920#issuecomment-1481607161

**Comment by jancborchardt** [comment]
Ref very similar issue https://github.com/nextcloud-libraries/nextcloud-vue/issues/3920#issuecomment-1484161068

**Comment by marcoambrosini** [comment]
So I think it's too late to touch the actions component. Modifying things there can cause all sorts of regressions everywhere and @szaimen rationale to use `50vh` makes sense. I'm trying to apply a fix for talk but for some reason the deep modifier doesn't work.

In `NcActions` I would add `overflow-y: scroll` so that the scroll bar is always shown. Relying on the last element being cut is a bit flaky and prone to failure.

this would be the result after the fix: 

[Screencast from 2023-11-21 13-50-58.webm](https://github.com/nextcloud-libraries/nextcloud-vue/assets/26852655/23ca2c41-1fa9-4316-a1d1-41bf369e8827)
