### ISSUE TITLE
bad character encoding

### ISSUE THREAD

**Issue by ndx1905-github** [nextcloud-libraries/nextcloud-vue#4657]
Some characters are not displayed correctly in the French version of a dashboard relying on vue.js.
It should spell "Fil d'actualités Mastodon" as in the title and not "Fil d'actualités Mastodon"
See screenshot
I created an[ issue](https://github.com/nextcloud/integration_mastodon/issues/53) in the dashboard repo, but the developer mentioned it was a problem with vue.js
![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/64833823/019f51ff-2314-4e31-86ec-4983228e8e97)

**Comment by susnux** [comment]
Hey,
which version of the mastodon integration are you using? Because that issue should be fixed with nextcloud vue 7 which is used by 1.0.5 of the mastodon integration.

**Comment by ndx1905-github** [comment]
Thanks for checking this. 
I try to have everything up to date so I use mastodon integration 2.02 on Nextcloud 27.1.2 and the problem is still there. 
If you look the screenshot it’s fixed for the title but not for the bottom of the dashboard.

**Comment by susnux** [comment]
Yes but that button should not contain "More {something}" since nextcloud-vue 7.0

---

But after having a look into that app, it is an app issue. The mastodon integration still uses `@nextcloud/vue-dashboard` which is deprecated and contains that bug.
The recommended way of fixing this is to migrate from `@nextcloud/vue-dashboard` to `@nextcloud/vue` and use `NcDashboardWidget`.
