### ISSUE TITLE
Add submenus to action menus 

### ISSUE THREAD

**Issue by marcoambrosini** [nextcloud-libraries/nextcloud-vue#4698]
I think that for this we should use floating-vue's submenus instead of our current strategy for actions

https://floating-vue.starpad.dev/guide/component#sub-menu

https://github.com/nextcloud/server/assets/26852655/5b5ded99-e949-4b75-a04d-f2c887e11bf4

ref https://github.com/nextcloud/server/pull/41010

cc @nextcloud-libraries/designers

**Comment by susnux** [comment]
Are we sure we ever want submenus? I remember some discussion with @jancborchardt but not sure how it ended :sweat_smile: 

I think the outcome was that submenus are bad for UX and we should rather use modals for more specific settings, but maybe I do not remember this correctly.

**Comment by nimishavijay** [comment]
We have used a "second level" menu in multiple places (send later in mail, remind me/snooze, more actions in mail, more properties in contacts) so I would say it is used enough that it could become a component. Agreed that we could use modals for specific settings though, I think having a "second level" menu is useful in its own right :) 

The styling of the components remains an open question though. This kind of cascading submenu is common on desktop apps, but it may not be responsive (not much available horizontal space on mobile screens) and may cause issues when the parent menu is on the corner of a screen. Since we also use this for "more actions" or "more items" the pagination pattern makes more sense than something that appears on the right. What do you think?

**Comment by szaimen** [comment]
> but it may not be responsive (not much available horizontal space on mobile screens) and may cause issues when the parent menu is on the corner of a screen. Since we also use this for "more actions" or "more items" the pagination pattern makes more sense than something that appears on the right. What do you think?

I agree 👍

**Comment by marcoambrosini** [comment]
👌
