### ISSUE TITLE
[NcAppSidebar] add `open` state

### ISSUE THREAD

**Issue by ShGKme** [nextcloud-libraries/nextcloud-vue#5335]
Currently `NcAppSidebar` doesn't have changeable `open` state. If it is rendered, it considers itself to be open. The only way to close the sidebar is basically to not render it like:

```html
<NcAppSidebar v-if="open" />
```

But some apps want to keep `NcAppSidebar` instance even if it is not displayed.
```html
<NcAppSidebar v-show="open" />
```

This breaks mobile devises, because `NcAppSidebar` consider itself open and enables a focus trap.

A solution could be to add `open` prop allowing to show/hide the sidebar keeping the component and the element in the DOM like `NcAppNavigation` does.

In this case, we can even render the toggle button like in Talk.

![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/25978914/51d9b76b-836b-4ebb-ba9a-dd90269f0325)

**Comment by Antreesy** [comment]
I'm afraid, same happens with NcAppNavigation too:

When it's in `mobile` state, focus trap is attached to toggle, and thus any open dialog would be inaccessible from keyboard (not saying that I couldn't type in TextField)
![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/93392545/9a23e1d1-ad30-4b9e-a32f-fd32e0958bb4)

**Comment by ShGKme** [comment]
Hmm, with dialog it should work. Dialogs are supposed to have a focus trap, so it should stack correctly

**Comment by ShGKme** [comment]
It is different with Sidebar. The sidebar issue in Talk is that Sidebar is actually open but visually hidden.

**Comment by adripo** [comment]
The issue is also present in cospend app. It happens with width < 512px.
https://github.com/julien-nc/cospend-nc/issues/248


When clicking on the textarea, the focus is attached to the logo link instead of the textarea when width < 512px.

width 511px:

![2024-03-21_03-41-46-939_brave](https://github.com/julien-nc/cospend-nc/assets/26493496/e2928b9a-d1e9-457d-8425-3ed12a7bb94b)

width 512px:

![2024-03-21_03-46-53-560_brave](https://github.com/julien-nc/cospend-nc/assets/26493496/9c5faab0-9aeb-4825-a3cf-e29483e10df8)
